version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  assignees:
  - franky47
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  assignees:
  - franky47
  ignore:
  - dependency-name: mhart/alpine-node
    versions:
    - ">= 15.a, < 16"
