name: Deploy to Clever Cloud
description: Deploy your application to Clever Cloud
author: Francois Best
branding:
  icon: upload-cloud
  color: red
inputs:
  alias:
    required: false
    description: |
      The alias of the application to deploy,
      if you are using a .clever.json file.
  appID:
    required: false
    description: |
      The ID of your application (can be found in the Clever Cloud console).
      Takes precedence over `alias` if both are defined.
runs:
  using: node12
  main: dist/index.js
